# In Makefile.run

STRATEGIES := mimic linear polynomial neural basic high-low wong
DECKS := single-deck double-deck six-shoe

# Default run parameters
HANDS ?= 500000000
THREADS ?= 24
STRATEGY ?= mimic
DECKS ?= single-deck

# Target name, etc.
TARGET = bin/striker-c
STRIKER = ${HOME}/Striker
LOG_DIR = $(STRIKER)/Simulations/$(shell date +%Y)/$(shell date +%m)/$(shell date +%d)
LOG = $(LOG_DIR)/$(notdir $(TARGET))-$(shell date +%H%M%S).log

# Main run template
define run_template
run-$(1)-$(2):
	@mkdir -p $(LOG_DIR)
	@echo "Running: $(1) strategy with $(2), $(HANDS) hands on $(THREADS) threads"
	clear
	./$(TARGET) --$(1) --$(2) --number-of-hands $(HANDS) --number-of-threads $(THREADS) | tee $(LOG)
	sleep 3
endef

# Generate targets
$(foreach strategy,$(STRATEGIES), \
	$(foreach deck,$(DECKS), \
		$(eval $(call run_template,$(strategy),$(deck))) \
	) \
)

# Strategy groups
define group_template
run-$(1):
	$(foreach deck,$(DECKS), \
		$(MAKE) run-$(1)-$(deck); \
	)
endef

$(foreach strategy,$(STRATEGIES), \
	$(eval $(call group_template,$(strategy))) \
)

# run-all
run-all:
	$(foreach strategy,$(STRATEGIES), \
		$(MAKE) run-$(strategy); \
	)

# Deck-based
run-single-deck:
	@for strategy in $(STRATEGIES); do \
		$(MAKE) run-$$strategy-single-deck; \
	done

run-double-deck:
	@for strategy in $(STRATEGIES); do \
		$(MAKE) run-$$strategy-double-deck; \
	done

run-six-shoe:
	@for strategy in $(STRATEGIES); do \
		$(MAKE) run-$$strategy-six-shoe; \
	done

# Aliases
r1: run-single-deck
r2: run-double-deck
r6: run-six-shoe

# Mimic
rm: run-mimic
rm1: run-mimic-single-deck
rm2: run-mimic-double-deck
rm6: run-mimic-six-shoe

# Linear
rl: run-linear
rl1: run-linear-single-deck
rl2: run-linear-double-deck
rl6: run-linear-six-shoe

# Polynomial
rp: run-polynomial
rp1: run-polynomial-single-deck
rp2: run-polynomial-double-deck
rp6: run-polynomial-six-shoe

# Neural
rn: run-neural
rn1: run-neural-single-deck
rn2: run-neural-double-deck
rn6: run-neural-six-shoe

# Basic
rb: run-basic
rb1: run-basic-single-deck
rb2: run-basic-double-deck
rb6: run-basic-six-shoe

# High-low
rh: run-high-low
rh1: run-high-low-single-deck
rh2: run-high-low-double-deck
rh6: run-high-low-six-shoe

# Wong
rw: run-wong
rw1: run-wong-single-deck
rw2: run-wong-double-deck
rw6: run-wong-six-shoe

